### ISSUE TITLE
DLL load failed: module not found

### ISSUE THREAD

**Issue by gauravjain2** [ashutoshvarma/ggsipu_result#2]
After doing pip install ggsipu-result
tried to run the following code:
`from ggsipu_result import iter_pages, has_page_results, iter_results
FILE="2015_032_B.TECH(CSE)_DECLARE_RESULT_DEC2019.pdf"
results = []
for page in iter_pages(FILE):
    if has_page_results(page):
        results = results + [r for r in iter_results(page) if r.batch == 2018]      
results.sort(key=lambda x: x.cgpa, reverse=True)
for i, result in enumerate(results[:-1]):
    print("{i}. {r}".format(i=i+1, r= result))`

the following error came:

> Traceback (most recent call last):
  File "abc.py", line 1, in <module>
    from ggsipu_result import iter_pages, has_page_results, iter_results
  File "C:\Users\JAIN\AppData\Local\Programs\Python\Python37\lib\site-packages\ggsipu_result\__init__.py", line 1, in <module>
    from pyxpdf import xpdf
  File "C:\Users\JAIN\AppData\Local\Programs\Python\Python37\lib\site-packages\pyxpdf\__init__.py", line 3, in <module>
    from pyxpdf.xpdf import (
ImportError: DLL load failed: The specified module could not be found.

**Comment by ashutoshvarma** [comment]
Unfortunately I cannot reproduce this in my machine.

Looks like PATH environment variable issue to me.
Can you share your PATH env value?
